name: container test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: windows image test
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-x86
      env:
          NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: ls
