name: container test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: windows image test
    runs-on: ubuntu-latest
    steps:
      - name: test hello world
        run: |
          docker pull dockcross/windows-shared-x86
          docker images
          docker run dockcross/windows-shared-x86 echo "hello from win x86"
          docker run -it busybox sh
          ls