name: windows test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: winget test
    runs-on: windows-2019
    steps:
      - name: test hello world
        run: |
          winget upgrade --all
          