name: windows test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: vc redist
        shell: powershell
        run: |
          Install-Module -Name "VcRedist" -Force
          Import-Module VcRedist
          $VcList = Get-VcList | Get-VcRedist -Path "D:\Temp\VcRedist"
          $VcList | Install-VcRedist -Path D:\Temp\VcRedist