name: windows test
on:
  push:
    branches: [master]

jobs:
  windows-build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: find mscvp
        shell: bash
        run: |
          ls -lh "c:/Windows/System32/"  

      - name: vc redist
        shell: powershell
        run: |
          Install-Module -Name "VcRedist" -Force
          Import-Module VcRedist
          $VcList = Get-VcList | Get-VcRedist -Path "D:/"
          $VcList | Install-VcRedist -Path D:/

      - name: find mscvp
        shell: bash
        run: |
          ls -lh "c:/Windows/System32/" 
