name: container test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: windows image test
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-shared-x86
    steps:
      - uses: actions/checkout@main
      - name: run ls
        run: |
          systeminfo
          