name: windows test
on:
  push:
    branches: [main]

jobs:
  windows-build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: vc redist
        shell: powershell
        run: |
          Set-Location "D:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "D:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd = @(
            "Microsoft.VisualStudio.Component.VC.Redist.MSM"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
              Write-Host "components have been successfully added"
          }
          else
          {
              Write-Host "components were not installed"
              exit 1
          }
      - run: |
          winget --info
          