name: container test
on:
  push:
    branches: [master]

jobs:
  windows-build:
    name: windows image test
    runs-on: ubuntu-latest
    steps:
      - name: test hello world
        run: |
          docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022
          docker images
          docker run -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe
          