name: container test
on:
  push:
    branches: [main]

jobs:
  windows-build:
  name: windows image test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/windows/servercore:ltsc2019
    steps:
      - name: ls test
        shell: bash
        run: |
          ls