name: release-python-gpu

on:
  push:
    branches: [main]
    # tags:
    #   - '*'


jobs:
  build_wheels:
    name: ${{ matrix.arch }} ${{ matrix.build }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, arch: x86_64,     build: 'cp*-manylinux*' }
          # - { os: ubuntu-20.04, arch: x86_64,     build: 'cp*-musllinux*' }
          # - { os: ubuntu-20.04, arch: x86_64,     build: 'pp*'            }
          # - { os: ubuntu-20.04, arch: i686,       build: 'cp*-manylinux*' }
          # - { os: ubuntu-20.04, arch: i686,       build: 'cp*-musllinux*' }
          # - { os: ubuntu-20.04, arch: i686,       build: 'pp*'            }
          # - { os: windows-2019, arch: x86,        build: 'cp*'            }
          # - { os: windows-2019, arch: AMD64,      build: 'cp*'            }
          # - { os: windows-2019, arch: AMD64,      build: 'pp*'            }
          # - { os: windows-2019, arch: ARM64,      build: 'cp*'            }
          # - { os: macos-latest, arch: x86_64,     build: 'cp*'            }
          # - { os: macos-latest, arch: x86_64,     build: 'pp*'            }
          # - { os: macos-latest, arch: arm64,      build: 'cp*'            }
          # - { os: macos-latest, arch: universal2, build: 'cp*'            }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: init submodules
        shell: bash
        run: |
          cd ncnn-python-gpu
          git submodule update --init
          cd python
          git submodule update --init

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # - name: check submodules
      #   shell: bash
      #   run: |
      #       cd ncnn-python-gpu
      #       ls -lh glslang
      #       cd python
      #       ls -lh pybind11
  
      - name: brew uninstall libomp
        if: matrix.os == 'macos-latest'
        run: |
          brew uninstall --ignore-dependencies libomp

      - name: cache-swiftshader
        id: cache-swiftshader
        uses: actions/cache@v3
        with:
          path: swiftshader-install
          key: swiftshader-linux-install-20230420
      - name: checkout-swiftshader
        if: steps.cache-swiftshader.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: google/swiftshader
          path: swiftshader
          ref: dd55e592406dc0bae219df11adec6363840aff4a
      - name: checkout-swiftshader-submodules
        if: steps.cache-swiftshader.outputs.cache-hit != 'true'
        run: |
          cd swiftshader
          git -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
      - name: swiftshader
        if: steps.cache-swiftshader.outputs.cache-hit != 'true'
        run: |
          cd swiftshader
          mkdir -p build; cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DSWIFTSHADER_BUILD_EGL=FALSE -DSWIFTSHADER_BUILD_GLESv2=FALSE -DSWIFTSHADER_BUILD_GLES_CM=FALSE -DSWIFTSHADER_BUILD_VULKAN=TRUE -DSWIFTSHADER_BUILD_PVR=FALSE -DSWIFTSHADER_BUILD_TESTS=FALSE -DSWIFTSHADER_ENABLE_ASTC=FALSE -DSWIFTSHADER_WARNINGS_AS_ERRORS=FALSE -DREACTOR_BACKEND=Subzero -DREACTOR_DEFAULT_OPT_LEVEL=Default -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j 4
          mkdir $GITHUB_WORKSPACE/swiftshader-install
          cp Linux/* $GITHUB_WORKSPACE/swiftshader-install
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ENVIRONMENT: CMAKE_BUILD_PARALLEL_LEVEL=2 NCNN_VULKAN='TRUE' 
        with:
          package-dir: ./ncnn-python-gpu
          output-dir: wheelhouse

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
        
